[2025-04-29T03:20:30.750+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-29T03:20:30.852+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: all_classification_pipeline.prepare_data manual__2025-04-29T03:15:52+00:00 [queued]>
[2025-04-29T03:20:30.917+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: all_classification_pipeline.prepare_data manual__2025-04-29T03:15:52+00:00 [queued]>
[2025-04-29T03:20:30.921+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-29T03:20:31.055+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): prepare_data> on 2025-04-29 03:15:52+00:00
[2025-04-29T03:20:31.074+0000] {standard_task_runner.py:72} INFO - Started process 106 to run task
[2025-04-29T03:20:31.085+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'all_classification_pipeline', 'prepare_data', 'manual__2025-04-29T03:15:52+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/classification_pipeline.py', '--cfg-path', '/tmp/tmpltjnbsof']
[2025-04-29T03:20:31.094+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask prepare_data
[2025-04-29T03:20:31.413+0000] {task_command.py:467} INFO - Running <TaskInstance: all_classification_pipeline.prepare_data manual__2025-04-29T03:15:52+00:00 [running]> on host 7f0efe64badc
[2025-04-29T03:20:32.391+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='all_classification_pipeline' AIRFLOW_CTX_TASK_ID='prepare_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-29T03:15:52+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-29T03:15:52+00:00'
[2025-04-29T03:20:32.394+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-29T03:20:32.416+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-29T03:20:32.418+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt && mlflow run . -e prepare_data -P raw_dir=/opt/data/processed -P out_dir=/opt/data/processed_manifest']
[2025-04-29T03:20:32.434+0000] {subprocess.py:99} INFO - Output:
[2025-04-29T03:20:32.438+0000] {subprocess.py:106} INFO - /usr/bin/bash: line 1: mlflow: command not found
[2025-04-29T03:20:32.439+0000] {subprocess.py:110} INFO - Command exited with return code 127
[2025-04-29T03:20:32.476+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-04-29T03:20:32.508+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=all_classification_pipeline, task_id=prepare_data, run_id=manual__2025-04-29T03:15:52+00:00, execution_date=20250429T031552, start_date=20250429T032030, end_date=20250429T032032
[2025-04-29T03:20:32.778+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-29T03:20:32.782+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 18 for task prepare_data (Bash command failed. The command returned a non-zero exit code 127.; 106)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-04-29T03:20:32.839+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-29T03:20:32.961+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-29T03:20:32.970+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
