[2025-04-29T06:27:59.313+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-29T06:27:59.434+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: all_classification_pipeline.train_classifier manual__2025-04-29T06:13:49.675488+00:00 [queued]>
[2025-04-29T06:27:59.527+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: all_classification_pipeline.train_classifier manual__2025-04-29T06:13:49.675488+00:00 [queued]>
[2025-04-29T06:27:59.533+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-29T06:27:59.688+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): train_classifier> on 2025-04-29 06:13:49.675488+00:00
[2025-04-29T06:27:59.760+0000] {standard_task_runner.py:72} INFO - Started process 952 to run task
[2025-04-29T06:27:59.882+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'all_classification_pipeline', 'train_classifier', 'manual__2025-04-29T06:13:49.675488+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/classification_pipeline.py', '--cfg-path', '/tmp/tmpcvtu83bq']
[2025-04-29T06:27:59.974+0000] {standard_task_runner.py:105} INFO - Job 33: Subtask train_classifier
[2025-04-29T06:28:00.624+0000] {task_command.py:467} INFO - Running <TaskInstance: all_classification_pipeline.train_classifier manual__2025-04-29T06:13:49.675488+00:00 [running]> on host 6654e0e8303a
[2025-04-29T06:28:01.388+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='all_classification_pipeline' AIRFLOW_CTX_TASK_ID='train_classifier' AIRFLOW_CTX_EXECUTION_DATE='2025-04-29T06:13:49.675488+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-29T06:13:49.675488+00:00'
[2025-04-29T06:28:01.402+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-29T06:28:02.641+0000] {logging_mixin.py:190} WARNING - 2025/04/29 06:28:02 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-04-29T06:28:05.822+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py:107 UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
[2025-04-29T06:28:07.154+0000] {logging_mixin.py:190} INFO - Epoch 1/3
[2025-04-29T06:28:46.903+0000] {local_task_job_runner.py:266} INFO - Task exited with return code -9. For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed
[2025-04-29T06:28:47.070+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-29T06:28:47.075+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
