[2025-04-29T06:21:03.114+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-29T06:21:03.177+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: all_classification_pipeline.train_classifier manual__2025-04-29T06:13:49.675488+00:00 [queued]>
[2025-04-29T06:21:03.216+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: all_classification_pipeline.train_classifier manual__2025-04-29T06:13:49.675488+00:00 [queued]>
[2025-04-29T06:21:03.219+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-29T06:21:03.310+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): train_classifier> on 2025-04-29 06:13:49.675488+00:00
[2025-04-29T06:21:03.338+0000] {standard_task_runner.py:72} INFO - Started process 828 to run task
[2025-04-29T06:21:03.351+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'all_classification_pipeline', 'train_classifier', 'manual__2025-04-29T06:13:49.675488+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/classification_pipeline.py', '--cfg-path', '/tmp/tmpuiy51byw']
[2025-04-29T06:21:03.362+0000] {standard_task_runner.py:105} INFO - Job 32: Subtask train_classifier
[2025-04-29T06:21:03.632+0000] {task_command.py:467} INFO - Running <TaskInstance: all_classification_pipeline.train_classifier manual__2025-04-29T06:13:49.675488+00:00 [running]> on host 6654e0e8303a
[2025-04-29T06:21:04.115+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='all_classification_pipeline' AIRFLOW_CTX_TASK_ID='train_classifier' AIRFLOW_CTX_EXECUTION_DATE='2025-04-29T06:13:49.675488+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-29T06:13:49.675488+00:00'
[2025-04-29T06:21:04.124+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-29T06:21:04.450+0000] {logging_mixin.py:190} WARNING - 2025/04/29 06:21:04 INFO mlflow.tracking.fluent: Experiment with name 'ALL_Classifier' does not exist. Creating a new experiment.
[2025-04-29T06:21:04.950+0000] {logging_mixin.py:190} WARNING - 2025/04/29 06:21:04 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-04-29T06:21:07.941+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py:107 UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
[2025-04-29T06:21:09.754+0000] {logging_mixin.py:190} INFO - Epoch 1/10
[2025-04-29T06:22:02.913+0000] {job.py:229} INFO - Heartbeat recovered after 13.27 seconds
[2025-04-29T06:22:02.963+0000] {local_task_job_runner.py:266} INFO - Task exited with return code -9. For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed
[2025-04-29T06:22:03.044+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-29T06:22:03.049+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
